{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "core.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "core.fullname" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "core.fullname" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        timestamp: "{{ .Values.global.timestamp }}"
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ template "core.fullname" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: api
    spec:
      {{ template "api.affinity" . }}
      {{ template "api.tolerations" . }}
      {{ template "api.nodeselector" . }}
      {{ template "api.hostAliases" . }}
      terminationGracePeriodSeconds: {{ .Values.api.terminationGracePeriodSeconds | default 300 }}
      containers:
        - name: core
          image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if .Values.api.command }}
          command: {{- toYaml .Values.api.command | nindent 10 }}
          args: {{ .Values.api.args }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort | default 80 }}
              protocol: TCP
          {{- if .Values.api.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .Values.api.readinessProbe.timeoutSeconds}}
            periodSeconds: 5
            successThreshold: 1
          {{- end }}
          {{ template "api.resources" . }}
          {{- if .Values.api.envFrom }}
          envFrom:
          {{- toYaml .Values.api.envFrom | nindent 10 }}
          {{- end }}
          env:
          {{ if .Values.global.datadog.enabled }}
          - name: DATADOG_TRACE_AGENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          {{ end }}
          {{- include "api.extraEnvironmentVars" .Values.api | nindent 10 }}
          {{- include "api.extraSecretEnvironmentVars" .Values.api | nindent 10 }}
         {{ template "api.mounts" . }}
         {{ template "api.volumes" . }}
{{- end }}